W0121 11:35:43.281000 371296 site-packages/torch/distributed/run.py:793] 
W0121 11:35:43.281000 371296 site-packages/torch/distributed/run.py:793] *****************************************
W0121 11:35:43.281000 371296 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0121 11:35:43.281000 371296 site-packages/torch/distributed/run.py:793] *****************************************
Traceback (most recent call last):
  File "/home/kha98/DiT/train.py", line 269, in <module>
    main(args)
  File "/home/kha98/DiT/train.py", line 114, in main
    assert torch.cuda.is_available(), "Training currently requires at least one GPU."
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Training currently requires at least one GPU.
Traceback (most recent call last):
  File "/home/kha98/DiT/train.py", line 269, in <module>
    main(args)
  File "/home/kha98/DiT/train.py", line 114, in main
    assert torch.cuda.is_available(), "Training currently requires at least one GPU."
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Training currently requires at least one GPU.
E0121 11:35:45.189000 371296 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 371309) of binary: /home/kha98/miniconda3/envs/DiT/bin/python
Traceback (most recent call last):
  File "/home/kha98/miniconda3/envs/DiT/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.5.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kha98/miniconda3/envs/DiT/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kha98/miniconda3/envs/DiT/lib/python3.12/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/kha98/miniconda3/envs/DiT/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/kha98/miniconda3/envs/DiT/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kha98/miniconda3/envs/DiT/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-01-21_11:35:45
  host      : cs-apex-09s
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 371310)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-21_11:35:45
  host      : cs-apex-09s
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 371309)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
